export enum Role {
  ADMIN = 'ADMIN',
  OPERATEUR_DE_PRODUCTION = 'OPERATEUR_DE_PRODUCTION',
  RESPONSABLE_DE_MAINTENANCE = 'RESPONSABLE_DE_MAINTENANCE',
  TECHNICIEN_DE_MAINTENANCE = 'TECHNICIEN_DE_MAINTENANCE',
  USER = 'USER',
}
